window.skills=[
  {
    'skill':'CSS',
    'image':'https://image.flaticon.com/icons/svg/732/732190.svg',
    'link':''
  },
  {
    'skill':'HTML',
    'image':'https://image.flaticon.com/icons/svg/174/174854.svg',
    'link':''
  },
  {
    'skill':'Javascript',
    'image':'https://image.flaticon.com/icons/svg/919/919828.svg',
    'link':''
  },
  {
    'skill':'Python',
    'image':'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Python.svg/360px-Python.svg.png',
    'link':''
  },
  {
    'skill':'Linux',
    'image':'https://www.shareicon.net/data/256x256/2016/09/23/833701_linux_512x512.png',
    'link':''
  },
  {
    'skill':'Polymer',
    'image':'https://d2eip9sf3oo6c2.cloudfront.net/tags/images/000/000/385/square_256/polymerjs.png',
    'link':''
  },
  {
    'skill':'NodeJS',
    'image':'https://nodejs.org/static/images/logo.svg',
    'link':''
  },
  {
    'skill':'Bash',
    'image':'https://cdn-images-1.medium.com/max/600/1*FEE98iWinlZBYkxBAG8MvA.png',
    'link':''
  },
  {
    'skill':'Git',
    'image':'https://git-scm.com/images/logos/downloads/Git-Icon-White.png',
    'link':''
  },
  {
    'skill':'DigitalOcean',
    'image':'https://www.macupdate.com/images/icons256/51075.png',
    'link':''
  },
  {
    'skill':'MongoDB',
    'image':'https://developer.asustor.com/uploadIcons/0020_13878_1388394236_mongodb.png',
    'link':''
  },
  {
    'skill':'Kotlin',
    'image':'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kotlin-logo.svg/220px-Kotlin-logo.svg.png',
    'link':''
  }
]
